help:
	@echo "\n Available tasks:"
	@echo "\t init - install prerequistes from requirements.txt"
	@echo "\t test - run all test from the test directory"

init:
	pip install -r requirements.txt

test:
	nosetests tests
